### ISSUE TITLE
NuGet Package Bump Requests

### ISSUE THREAD

**Issue by BeachyHeadCode** [adamfoneil/JsonSettings#10]
Could the packages be updated:

- [ ] **System.Security.Cryptography.ProtectedData** from 7.0.0 to 8.0.0
- [ ] **Newtonsoft.Json** from 13.0.1 to 13.0.3

While they pass on my build would like for you to check yourself and possibly have the dependabot create the pull request.

**Comment by adamfoneil** [comment]
@BeachyHeadCode will get the updated packages out later today. Thanks for the fix on #8

**Comment by adamfoneil** [comment]
ok I pushed v1.1.2 with package updates
