### ISSUE TITLE
Newtonsoft.json 13.0.1 build needed

### ISSUE THREAD

**Issue by MrPlow254** [adamfoneil/JsonSettings#4]
Looks like the package text was updated, but the dll compiled does not contain that version it references 12.0.0.

**Comment by adamfoneil** [comment]
I'm not working on this, but feel free to submit PR with update

**Comment by MrPlow254** [comment]
No changes to the code are required for this. The library just needs to be built. It wasn't built right. So all that needs to be done is in your solution, right click on ' JsonSettings.Library' click Build, then upload to nuget.

**Comment by adamfoneil** [comment]
done as package version 1.1.0
https://www.nuget.org/packages/JsonSettings.Library/#release-body-tab
