### ISSUE TITLE
test failing after recent changes

### ISSUE THREAD

**Issue by adamfoneil** [adamfoneil/JsonSettings#8]
Thanks @BeachyHeadCode for your recent PRs, but I see that this test is failing now

https://github.com/adamfoneil/JsonSettings/blob/master/JsonSettings.Test/AllTests.cs#L51

**Comment by BeachyHeadCode** [comment]
@adamfoneil Figured it out. I never set the variable added to decrypted text. https://github.com/adamfoneil/JsonSettings/blob/ab64b13c0f846effb07684bb43acc94f30ffbfa3/JsonSettings.Library/JsonProtectAttribute.cs#L91

Should have done this: `decryptedText =DataProtection.Decrypt(encryptedText, Scope);`

I apologize for the incomplete logic.

**Comment by BeachyHeadCode** [comment]
See changes in pull request https://github.com/adamfoneil/JsonSettings/pull/9
